version: '3'
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - 80:80
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    entrypoint: >
      sh -c "certbot certonly --standalone --non-interactive --agree-tos --email vaviknai@gmail.com -d slavchik.space || echo 'Certbot failed or cert already exists'"

volumes:
  certbot-etc:

networks:
  shinobi-net:
    driver: bridge
