version: '3'
services:
  shinobi:
    build:
      context: .
      args:
        SHINOBI_BRANCH: dev
    volumes:
      - /dev/shm/ShinobiRAM:/dev/shm/streams
      - $HOME/Shinobi:/home/Shinobi
 #     - /dev/video0:/dev/video0
    ports:
      - "8080:8080"
    environment:
      - HOME=/home/Shinobi
      - DB_HOST=shinobi-sql
      - DB_USER=majesticflame
      - DB_PASSWORD=1234
      - DB_DATABASE=ccio
      - SHINOBI_UPDATE=false
    restart: unless-stopped
#    network_mode: "host"
#    devices:
#      - "/dev/video0:/dev/video0"
